fix: Make YAML can convert to GameMap Type
java.lang.IllegalArgumentException: Unrecognized field "x" (class com.zeroninefivefive.wcnm.Arena.Stages.KillerSpawn), not marked as ignorable (2 known properties: "spawn", "door"])